-- ============================================================================
-- BANCO BANQUITO V2 - IDENTITY & ACCESS SERVICE
-- Modelo fisico MySQL 8.4 LTS
-- Base: banquito_identity_access_db
-- Proposito: autenticacion, autorizacion, RBAC, sesiones, API clients, scopes,
-- MFA, auditoria de seguridad y eventos outbox.
-- Principios: Database per Service, VARCHAR + CHECK para enums, UUIDs,
-- PK/FK/UK/CK nombradas, InnoDB, utf8mb4.
-- ============================================================================

CREATE DATABASE IF NOT EXISTS banquito_identity_access_db
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;
USE banquito_identity_access_db;

SET FOREIGN_KEY_CHECKS = 0;
DROP VIEW IF EXISTS V_USUARIO_PERMISOS;
DROP TABLE IF EXISTS OUTBOX_EVENT;
DROP TABLE IF EXISTS AUDITORIA_SEGURIDAD;
DROP TABLE IF EXISTS MFA_FACTOR;
DROP TABLE IF EXISTS API_CLIENT_SCOPE;
DROP TABLE IF EXISTS API_CLIENT;
DROP TABLE IF EXISTS SESION_USUARIO;
DROP TABLE IF EXISTS ROL_PERMISO;
DROP TABLE IF EXISTS USUARIO_ROL;
DROP TABLE IF EXISTS PERMISO;
DROP TABLE IF EXISTS ROL;
DROP TABLE IF EXISTS PARAMETRO_SEGURIDAD;
DROP TABLE IF EXISTS USUARIO_IDENTIDAD;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE USUARIO_IDENTIDAD (
  ID BIGINT AUTO_INCREMENT NOT NULL COMMENT 'Identificador interno de identidad',
  UUID_USUARIO CHAR(36) NOT NULL COMMENT 'Identificador global de usuario/actor',
  TIPO_ACTOR VARCHAR(15) NOT NULL COMMENT 'CLIENTE, EMPLEADO o SERVICIO',
  USERNAME VARCHAR(80) NOT NULL COMMENT 'Nombre de usuario unico',
  EMAIL VARCHAR(160) NULL COMMENT 'Correo principal verificable',
  EMAIL_VERIFICADO TINYINT(1) NOT NULL DEFAULT 0 COMMENT '1=correo verificado',
  TELEFONO_MOVIL VARCHAR(25) NULL COMMENT 'Telefono para MFA/notificaciones',
  PASSWORD_HASH VARCHAR(255) NULL COMMENT 'Hash fuerte de password; null en cuentas tecnicas sin login humano',
  PASSWORD_ALGORITHM VARCHAR(30) NULL DEFAULT 'BCrypt' COMMENT 'Algoritmo usado: BCrypt/Argon2id',
  PASSWORD_UPDATED_AT DATETIME NULL COMMENT 'Ultimo cambio de password',
  REQUIERE_CAMBIO_PASSWORD TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Obliga cambio de clave en siguiente login',
  ESTADO VARCHAR(20) NOT NULL DEFAULT 'ACTIVO' COMMENT 'Estado de la identidad',
  INTENTOS_FALLIDOS INT NOT NULL DEFAULT 0 COMMENT 'Intentos fallidos consecutivos',
  BLOQUEADO_HASTA DATETIME NULL COMMENT 'Bloqueo temporal por seguridad',
  ULTIMO_LOGIN DATETIME NULL COMMENT 'Ultimo login exitoso',
  UUID_REFERENCIA_EXTERNA CHAR(36) NULL COMMENT 'UUID de cliente/empleado en microservicio propietario; sin FK cruzada',
  REFERENCIA_TIPO VARCHAR(30) NULL COMMENT 'CUSTOMER, CORE_USER, SERVICE, etc.',
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  VERSION INT NOT NULL DEFAULT 0 COMMENT 'Version para concurrencia optimista',
  CONSTRAINT PK_USUARIO_IDENTIDAD PRIMARY KEY (ID),
  CONSTRAINT UK_USUARIO_IDENTIDAD_UUID UNIQUE (UUID_USUARIO),
  CONSTRAINT UK_USUARIO_IDENTIDAD_USERNAME UNIQUE (USERNAME),
  CONSTRAINT UK_USUARIO_IDENTIDAD_EMAIL UNIQUE (EMAIL),
  CONSTRAINT CK_USUARIO_IDENTIDAD_TIPO CHECK (TIPO_ACTOR IN ('CLIENTE','EMPLEADO','SERVICIO')),
  CONSTRAINT CK_USUARIO_IDENTIDAD_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO','BLOQUEADO','PENDIENTE','REVOCADO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Identidades autenticables humanas o tecnicas';

CREATE TABLE PARAMETRO_SEGURIDAD (
  CODIGO VARCHAR(60) NOT NULL,
  NOMBRE VARCHAR(120) NOT NULL,
  VALOR_TEXTO VARCHAR(300) NOT NULL,
  TIPO_DATO VARCHAR(20) NOT NULL DEFAULT 'STRING',
  DESCRIPCION VARCHAR(500) NULL,
  ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVO',
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  VERSION INT NOT NULL DEFAULT 0,
  CONSTRAINT PK_PARAMETRO_SEGURIDAD PRIMARY KEY (CODIGO),
  CONSTRAINT CK_PARAMETRO_SEG_TIPO CHECK (TIPO_DATO IN ('STRING','INTEGER','DECIMAL','BOOLEAN','TIME','JSON')),
  CONSTRAINT CK_PARAMETRO_SEG_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Parametros globales de seguridad';

CREATE TABLE ROL (
  ID INT AUTO_INCREMENT NOT NULL,
  CODIGO VARCHAR(60) NOT NULL,
  NOMBRE VARCHAR(120) NOT NULL,
  DESCRIPCION VARCHAR(300) NULL,
  TIPO_ROL VARCHAR(15) NOT NULL COMMENT 'INTERNO, CLIENTE o SERVICIO',
  ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVO',
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  VERSION INT NOT NULL DEFAULT 0,
  CONSTRAINT PK_ROL PRIMARY KEY (ID),
  CONSTRAINT UK_ROL_CODIGO UNIQUE (CODIGO),
  CONSTRAINT CK_ROL_TIPO CHECK (TIPO_ROL IN ('INTERNO','CLIENTE','SERVICIO')),
  CONSTRAINT CK_ROL_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Roles RBAC';

CREATE TABLE PERMISO (
  ID INT AUTO_INCREMENT NOT NULL,
  CODIGO VARCHAR(100) NOT NULL COMMENT 'Permiso granular o scope funcional',
  NOMBRE VARCHAR(150) NOT NULL,
  MODULO VARCHAR(50) NOT NULL COMMENT 'AUTH, CUSTOMER, ADMIN, ACCOUNT, ACCOUNTING, SWITCH, DOCUMENT, NOTIFICATION',
  ACCION VARCHAR(50) NOT NULL COMMENT 'READ, CREATE, UPDATE, DELETE, EXECUTE, APPROVE, etc.',
  RECURSO VARCHAR(80) NOT NULL COMMENT 'Recurso protegido',
  ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVO',
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  VERSION INT NOT NULL DEFAULT 0,
  CONSTRAINT PK_PERMISO PRIMARY KEY (ID),
  CONSTRAINT UK_PERMISO_CODIGO UNIQUE (CODIGO),
  CONSTRAINT CK_PERMISO_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Permisos granulares RBAC';

CREATE TABLE USUARIO_ROL (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  USUARIO_ID BIGINT NOT NULL,
  ROL_ID INT NOT NULL,
  ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVO',
  ASIGNADO_POR_UUID CHAR(36) NULL,
  FECHA_ASIGNACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_REVOCACION DATETIME NULL,
  CONSTRAINT PK_USUARIO_ROL PRIMARY KEY (ID),
  CONSTRAINT UK_USUARIO_ROL UNIQUE (USUARIO_ID, ROL_ID),
  CONSTRAINT FK_USUARIO_ROL_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO_IDENTIDAD(ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT FK_USUARIO_ROL_ROL FOREIGN KEY (ROL_ID) REFERENCES ROL(ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT CK_USUARIO_ROL_ESTADO CHECK (ESTADO IN ('ACTIVO','REVOCADO','INACTIVO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Asignacion de roles a usuarios';

CREATE TABLE ROL_PERMISO (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  ROL_ID INT NOT NULL,
  PERMISO_ID INT NOT NULL,
  ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVO',
  FECHA_ASIGNACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_ROL_PERMISO PRIMARY KEY (ID),
  CONSTRAINT UK_ROL_PERMISO UNIQUE (ROL_ID, PERMISO_ID),
  CONSTRAINT FK_ROL_PERMISO_ROL FOREIGN KEY (ROL_ID) REFERENCES ROL(ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT FK_ROL_PERMISO_PERMISO FOREIGN KEY (PERMISO_ID) REFERENCES PERMISO(ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT CK_ROL_PERMISO_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Permisos asignados a roles';

CREATE TABLE SESION_USUARIO (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  UUID_SESION CHAR(36) NOT NULL,
  USUARIO_ID BIGINT NOT NULL,
  ACCESS_TOKEN_JTI CHAR(36) NULL COMMENT 'JTI del JWT emitido',
  REFRESH_TOKEN_HASH VARCHAR(255) NULL COMMENT 'Hash de refresh token, nunca token plano',
  IP_ORIGEN VARCHAR(45) NULL,
  USER_AGENT VARCHAR(500) NULL,
  ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVA',
  FECHA_INICIO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_EXPIRACION DATETIME NOT NULL,
  FECHA_CIERRE DATETIME NULL,
  MOTIVO_CIERRE VARCHAR(200) NULL,
  CONSTRAINT PK_SESION_USUARIO PRIMARY KEY (ID),
  CONSTRAINT UK_SESION_UUID UNIQUE (UUID_SESION),
  CONSTRAINT UK_SESION_JTI UNIQUE (ACCESS_TOKEN_JTI),
  CONSTRAINT FK_SESION_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO_IDENTIDAD(ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT CK_SESION_ESTADO CHECK (ESTADO IN ('ACTIVA','EXPIRADA','REVOCADA','CERRADA'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Sesiones y refresh tokens';

CREATE TABLE API_CLIENT (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  CLIENT_ID VARCHAR(100) NOT NULL COMMENT 'Identificador OAuth2/client credentials',
  CLIENT_SECRET_HASH VARCHAR(255) NOT NULL COMMENT 'Hash del secreto tecnico',
  NOMBRE VARCHAR(150) NOT NULL,
  SERVICIO_ORIGEN VARCHAR(80) NOT NULL COMMENT 'Servicio propietario del cliente tecnico',
  TIPO_CLIENTE VARCHAR(20) NOT NULL DEFAULT 'SERVICE',
  ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVO',
  FECHA_EXPIRACION DATETIME NULL,
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  VERSION INT NOT NULL DEFAULT 0,
  CONSTRAINT PK_API_CLIENT PRIMARY KEY (ID),
  CONSTRAINT UK_API_CLIENT_ID UNIQUE (CLIENT_ID),
  CONSTRAINT CK_API_CLIENT_TIPO CHECK (TIPO_CLIENTE IN ('SERVICE','GATEWAY','EXTERNAL')),
  CONSTRAINT CK_API_CLIENT_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO','REVOCADO','EXPIRADO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Clientes tecnicos para autenticacion servicio a servicio';

CREATE TABLE API_CLIENT_SCOPE (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  API_CLIENT_ID BIGINT NOT NULL,
  SCOPE VARCHAR(120) NOT NULL,
  DESCRIPCION VARCHAR(300) NULL,
  ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVO',
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_API_CLIENT_SCOPE PRIMARY KEY (ID),
  CONSTRAINT UK_API_CLIENT_SCOPE UNIQUE (API_CLIENT_ID, SCOPE),
  CONSTRAINT FK_API_CLIENT_SCOPE_CLIENT FOREIGN KEY (API_CLIENT_ID) REFERENCES API_CLIENT(ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT CK_API_CLIENT_SCOPE_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Scopes permitidos por cliente tecnico';

CREATE TABLE MFA_FACTOR (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  USUARIO_ID BIGINT NOT NULL,
  TIPO_FACTOR VARCHAR(20) NOT NULL COMMENT 'TOTP, SMS, EMAIL',
  SECRETO_CIFRADO VARBINARY(512) NULL COMMENT 'Secreto cifrado o referencia segura',
  DESTINO_ENMASCARADO VARCHAR(120) NULL,
  ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVO',
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ULTIMO_USO DATETIME NULL,
  CONSTRAINT PK_MFA_FACTOR PRIMARY KEY (ID),
  CONSTRAINT FK_MFA_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO_IDENTIDAD(ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT CK_MFA_TIPO CHECK (TIPO_FACTOR IN ('TOTP','SMS','EMAIL')),
  CONSTRAINT CK_MFA_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO','REVOCADO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Factores MFA por usuario';

CREATE TABLE AUDITORIA_SEGURIDAD (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  UUID_CORRELACION CHAR(36) NULL,
  USUARIO_ID BIGINT NULL,
  API_CLIENT_ID BIGINT NULL,
  EVENTO VARCHAR(60) NOT NULL,
  RESULTADO VARCHAR(15) NOT NULL,
  IP_ORIGEN VARCHAR(45) NULL,
  USER_AGENT VARCHAR(500) NULL,
  DETALLE_JSON JSON NULL,
  FECHA_EVENTO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_AUDITORIA_SEGURIDAD PRIMARY KEY (ID),
  CONSTRAINT FK_AUDIT_SEG_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO_IDENTIDAD(ID) ON UPDATE RESTRICT ON DELETE SET NULL,
  CONSTRAINT FK_AUDIT_SEG_CLIENT FOREIGN KEY (API_CLIENT_ID) REFERENCES API_CLIENT(ID) ON UPDATE RESTRICT ON DELETE SET NULL,
  CONSTRAINT CK_AUDIT_SEG_RESULTADO CHECK (RESULTADO IN ('OK','ERROR','DENEGADO','ALERTA'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Auditoria de seguridad y accesos';

CREATE TABLE OUTBOX_EVENT (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  UUID_EVENTO CHAR(36) NOT NULL,
  UUID_CORRELACION CHAR(36) NULL,
  TIPO_EVENTO VARCHAR(80) NOT NULL,
  AGREGADO_TIPO VARCHAR(80) NOT NULL,
  AGREGADO_ID VARCHAR(80) NOT NULL,
  PAYLOAD_JSON JSON NOT NULL,
  ESTADO VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
  INTENTOS INT NOT NULL DEFAULT 0,
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_PUBLICACION DATETIME NULL,
  ERROR_ULTIMO VARCHAR(1000) NULL,
  CONSTRAINT PK_OUTBOX_IDENTITY PRIMARY KEY (ID),
  CONSTRAINT UK_OUTBOX_IDENTITY_UUID UNIQUE (UUID_EVENTO),
  CONSTRAINT CK_OUTBOX_IDENTITY_ESTADO CHECK (ESTADO IN ('PENDIENTE','PUBLICADO','ERROR','DESCARTADO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Eventos confiables para notificaciones/auditoria';

CREATE VIEW V_USUARIO_PERMISOS AS
SELECT u.UUID_USUARIO, u.USERNAME, r.CODIGO AS ROL, p.CODIGO AS PERMISO
FROM USUARIO_IDENTIDAD u
JOIN USUARIO_ROL ur ON ur.USUARIO_ID = u.ID AND ur.ESTADO = 'ACTIVO'
JOIN ROL r ON r.ID = ur.ROL_ID AND r.ESTADO = 'ACTIVO'
JOIN ROL_PERMISO rp ON rp.ROL_ID = r.ID AND rp.ESTADO = 'ACTIVO'
JOIN PERMISO p ON p.ID = rp.PERMISO_ID AND p.ESTADO = 'ACTIVO';

CREATE INDEX IDX_USUARIO_ESTADO ON USUARIO_IDENTIDAD(ESTADO);
CREATE INDEX IDX_AUDITORIA_SEG_FECHA ON AUDITORIA_SEGURIDAD(FECHA_EVENTO);
CREATE INDEX IDX_OUTBOX_IDENTITY_ESTADO ON OUTBOX_EVENT(ESTADO, FECHA_CREACION);

INSERT INTO PARAMETRO_SEGURIDAD (CODIGO,NOMBRE,VALOR_TEXTO,TIPO_DATO,DESCRIPCION) VALUES
('PASSWORD_MIN_LENGTH','Longitud minima password','10','INTEGER','Minimo de caracteres para passwords'),
('MAX_FAILED_ATTEMPTS','Intentos fallidos maximos','5','INTEGER','Bloqueo temporal despues de intentos fallidos'),
('ACCESS_TOKEN_MINUTES','Duracion access token','15','INTEGER','Minutos de validez del JWT'),
('REFRESH_TOKEN_DAYS','Duracion refresh token','7','INTEGER','Dias de validez refresh token');

INSERT INTO ROL (CODIGO,NOMBRE,TIPO_ROL,DESCRIPCION) VALUES
('ADMIN_SEGURIDAD','Administrador de seguridad','INTERNO','Gestiona usuarios, roles y permisos'),
('CAJERO','Cajero de sucursal','INTERNO','Opera ventanilla'),
('OPERADOR_CONTABLE','Operador contable','INTERNO','Ejecuta tareas contables y EOD'),
('CLIENTE_PERSONA','Cliente persona natural','CLIENTE','Acceso de banca web personas'),
('CLIENTE_EMPRESA','Cliente empresa','CLIENTE','Acceso de banca web empresas'),
('SWITCH_SERVICE','Servicio Switch','SERVICIO','Cliente tecnico del Switch hacia Core'),
('CORE_SERVICE','Servicio Core interno','SERVICIO','Cliente tecnico entre microservicios Core');

INSERT INTO PERMISO (CODIGO,NOMBRE,MODULO,ACCION,RECURSO) VALUES
('auth.user.manage','Gestionar usuarios','AUTH','MANAGE','USER'),
('core.customer.read','Consultar clientes','CUSTOMER','READ','CUSTOMER'),
('core.customer.create','Crear clientes','CUSTOMER','CREATE','CUSTOMER'),
('core.admin.config.read','Leer configuracion','ADMIN','READ','CONFIG'),
('core.admin.config.update','Actualizar configuracion','ADMIN','UPDATE','CONFIG'),
('core.account.balance.read','Consultar saldo','ACCOUNT','READ','BALANCE'),
('core.account.debit','Debitar cuenta','ACCOUNT','EXECUTE','DEBIT'),
('core.account.credit','Acreditar cuenta','ACCOUNT','EXECUTE','CREDIT'),
('core.account.transfer.p2p','Transferencia P2P','ACCOUNT','EXECUTE','TRANSFER'),
('core.teller.deposit','Deposito ventanilla','ACCOUNT','EXECUTE','TELLER_DEPOSIT'),
('core.teller.withdrawal','Retiro ventanilla','ACCOUNT','EXECUTE','TELLER_WITHDRAWAL'),
('core.reserve.create','Crear reserva pago masivo','ACCOUNT','CREATE','RESERVE'),
('core.reserve.consume','Consumir reserva pago masivo','ACCOUNT','EXECUTE','RESERVE_CONSUME'),
('core.reserve.release','Liberar reserva pago masivo','ACCOUNT','EXECUTE','RESERVE_RELEASE'),
('core.accounting.entry.create','Crear asiento contable','ACCOUNTING','CREATE','JOURNAL_ENTRY'),
('core.accounting.eod.run','Ejecutar EOD','ACCOUNTING','EXECUTE','EOD'),
('document.create','Crear documento','DOCUMENT','CREATE','DOCUMENT'),
('notification.send','Enviar notificacion','NOTIFICATION','EXECUTE','NOTIFICATION');

-- Asignaciones iniciales minimas de permisos por rol
INSERT INTO ROL_PERMISO (ROL_ID, PERMISO_ID)
SELECT r.ID, p.ID FROM ROL r JOIN PERMISO p
WHERE (r.CODIGO='ADMIN_SEGURIDAD' AND p.CODIGO IN ('auth.user.manage'))
   OR (r.CODIGO='CAJERO' AND p.CODIGO IN ('core.customer.read','core.account.balance.read','core.teller.deposit','core.teller.withdrawal'))
   OR (r.CODIGO='OPERADOR_CONTABLE' AND p.CODIGO IN ('core.accounting.entry.create','core.accounting.eod.run'))
   OR (r.CODIGO='CLIENTE_PERSONA' AND p.CODIGO IN ('core.account.balance.read','core.account.transfer.p2p'))
   OR (r.CODIGO='CLIENTE_EMPRESA' AND p.CODIGO IN ('core.account.balance.read'))
   OR (r.CODIGO='SWITCH_SERVICE' AND p.CODIGO IN ('core.reserve.create','core.reserve.consume','core.reserve.release','core.account.credit','core.account.debit'))
   OR (r.CODIGO='CORE_SERVICE' AND p.CODIGO IN ('core.accounting.entry.create','document.create','notification.send'));

INSERT INTO API_CLIENT (CLIENT_ID, CLIENT_SECRET_HASH, NOMBRE, SERVICIO_ORIGEN, TIPO_CLIENTE) VALUES
('banquito-core-api-gateway','CHANGE_ME_HASH','Core API Gateway','banquito-core-api-gateway','GATEWAY'),
('banquito-switch-api-gateway','CHANGE_ME_HASH','Switch API Gateway','banquito-switch-api-gateway','GATEWAY'),
('core-account-service','CHANGE_ME_HASH','Core Account Service','core-account-service','SERVICE'),
('core-accounting-service','CHANGE_ME_HASH','Core Accounting Service','core-accounting-service','SERVICE'),
('switch-pagos-internos-service','CHANGE_ME_HASH','Switch Pagos Internos','switch-pagos-internos-service','SERVICE');

INSERT INTO API_CLIENT_SCOPE (API_CLIENT_ID, SCOPE)
SELECT c.ID, s.SCOPE FROM API_CLIENT c
JOIN (
  SELECT 'banquito-core-api-gateway' CLIENT_ID, 'gateway.core.route' SCOPE UNION ALL
  SELECT 'banquito-switch-api-gateway','gateway.switch.route' UNION ALL
  SELECT 'core-account-service','core.accounting.entry.create' UNION ALL
  SELECT 'core-account-service','notification.send' UNION ALL
  SELECT 'core-accounting-service','document.create' UNION ALL
  SELECT 'switch-pagos-internos-service','core.reserve.create' UNION ALL
  SELECT 'switch-pagos-internos-service','core.reserve.consume' UNION ALL
  SELECT 'switch-pagos-internos-service','core.reserve.release'
) s ON s.CLIENT_ID = c.CLIENT_ID;
